services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: API
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__RedisConnectionString=${REDIS_CONNECTION}
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Subject=${JWT_SUBJECT}
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=FitPro
      - ASPNETCORE_DATAPROTECTION__PERSISTKEYSTOFILESYSTEM=/root/.aspnet/DataProtection-Keys
      - ConnectionStrings__pgconn=Server=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};UserId=${DB_USER};Password=${DB_PASS}
      - RecaptchaSettings__SiteKey=${RECAPTCHA_SITE_KEY}
      - RecaptchaSettings__SecretKey=${RECAPTCHA_SECRET_KEY}
    networks:
      - FitPro-network
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - dpkeys:/root/.aspnet/DataProtection-Keys

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: MVC
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__RedisConnectionString=${REDIS_CONNECTION}
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Subject=${JWT_SUBJECT}
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=FitPro
      - ASPNETCORE_DATAPROTECTION__PERSISTKEYSTOFILESYSTEM=/root/.aspnet/DataProtection-Keys
      - ConnectionStrings__pgconn=Server=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};UserId=${DB_USER};Password=${DB_PASS}
      - RecaptchaSettings__SiteKey=${RECAPTCHA_SITE_KEY}
      - RecaptchaSettings__SecretKey=${RECAPTCHA_SECRET_KEY}
    networks:
      - FitPro-network
    depends_on:
      - api
      - redis
      - rabbitmq
    volumes:
      - dpkeys:/root/.aspnet/DataProtection-Keys

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - FitPro-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - FitPro-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  FitPro-network:
    driver: bridge

volumes:
  dpkeys:
  redis-data:
  rabbitmq-data:
