services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: API
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - EduTrackPro-network

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: MVC
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - EduTrackPro-network
    depends_on:
      - api

networks:
  EduTrackPro-network:
    driver: bridge
